# Site settings
title: Will Hopkins
email: will@williamjhopkins.org
description: > # this means to ignore newlines until "baseurl:"
  I got words.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://willhopkins.github.io" # the base hostname & protocol for your site
twitter_username: willjhopkins
github_username:  willhopkins

# Build settings
markdown: kramdown
